<a href="https://colab.research.google.com/github/gamboapinzond-cmd/programacion-1/blob/main/parcial2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np #131 y 197
A = ([132, 133, 134, 134, 136, 137, 138,139, 150, 151,152,153,154,155,156,157,158,159,161,149,147,142,147,143,141,140,172,174,145,171,161, 162,163,164,165,166,167,168,169,170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 181])
np.random.seed(0)
datos = np.random.randint(131, 197, 50)

In [35]:
import pandas as pd
x = A
x = pd.DataFrame(x)
normalizar = lambda x: (x - x.mean()) / x.std()
resultado = normalizar(x)
print(resultado)

           0
0  -1.746679
1  -1.677966
2  -1.609253
3  -1.609253
4  -1.471827
5  -1.403115
6  -1.334402
7  -1.265689
8  -0.509849
9  -0.441136
10 -0.372423
11 -0.303710
12 -0.234998
13 -0.166285
14 -0.097572
15 -0.028859
16  0.039853
17  0.108566
18  0.245992
19 -0.578562
20 -0.715987
21 -1.059551
22 -0.715987
23 -0.990838
24 -1.128264
25 -1.196976
26  1.001832
27  1.139258
28 -0.853413
29  0.933119
30  0.245992
31  0.314704
32  0.383417
33  0.452130
34  0.520843
35  0.589556
36  0.658268
37  0.726981
38  0.795694
39  0.864407
40  0.933119
41  1.001832
42  1.070545
43  1.139258
44  1.207970
45  1.276683
46  1.345396
47  1.414109
48  1.482822
49  1.620247

In [36]:
x.describe()

                0
count   50.000000
mean   157.420000
std     14.553336
min    132.000000
25%    145.500000
50%    158.500000
75%    170.750000
max    181.000000

In [41]:
f = pd.DataFrame(datos)
f.describe()

             0         1       2      3
count        6         6       6      6
unique       6         6       6      5
top     Nombre  vocacion  edades  10000
freq         1         1       1      2

In [20]:
import pandas as pd
nombres = (["ana", "pedro", "rodolfo", "Ernesto", "maira"])
vocacion = (["camarera", "carpintero", "constructor", "ingeniero", "cocinera"])
edades = ([19, 20, 32, 23, 21])
salario = ([10000, 12000, 13000, 23000, 10000])
pd.DataFrame({"nombres": nombres, "vocacion": vocacion, "edades": edades, "salario": salario})

   nombres     vocacion  edades  salario
0      ana     camarera      19    10000
1    pedro   carpintero      20    12000
2  rodolfo  constructor      32    13000
3  Ernesto    ingeniero      23    23000
4    maira     cocinera      21    10000

In [23]:
Data = pd.DataFrame.from_dict({"nombres": nombres, "vocacion": vocacion, "edades": edades, "salario": salario})

In [28]:
Data.head(1)

  nombres  vocacion  edades  salario
0     ana  camarera      19    10000

In [30]:
# CREAR UN CSV:
from google.colab import files
import csv
datos = [
    ["Nombre", "vocacion", "edades", "salario"],
    ["Ana", "camarera", 19, 10000],
    ["Pedro", "carpintero", 20, 12000],
    ["Rodolfo", "constructor", 32, 13000],
     ["ernesto", "ingeniero", 23, 23000],
     ["maira", "cocinera", 21, 10000]

]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

files.download("datos.csv")

In [ ]:
# CREAR UN CSV:
from google.colab import files
import csv
datos = [
    ["Nombre", "vocacion", "edades", "salario"],
    ["Ana", "camarera", "19", "10000"],
    ["Pedro", "carpintero", "20", "12000],
    ["Rodolfo", "constructor", "32", "13000"],
     ["ernesto", "ingeniero", "23", "23000"],
     ["maira", "cocinera", "21", "10000"]

]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

files.download("datos.csv")

# CREAR MODULOS Y PAQUETES:

import os
os.makedirs("op", exist_ok=True)

%%writefile op/operaciones.py

# FUNCION LAMBDA
import pandas as pd
x = [1, 2, 3, 4]
x = pd.DataFrame(x)
normalizar = lambda x: (x - x.mean()) / x.std()
resultado = normalizar(x)
print(resultado)